version: '2'

services:
  consul:
    image: progrium/consul:latest
    container_name: consul
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:53/udp
    hostname: consul
    command: "-server -bootstrap -ui-dir /ui"

  registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: "-internal consul://127.0.0.1:8500/services"
    network_mode: "host"
    depends_on:
      - consul

  nginx:
    build: ./container/nginx
    image: microservice:nginx
    container_name: nginx
    depends_on:
      - consul
    ports:
      - 80:80
    volumes:
      - ./container/nginx/service.ctmpl:/templates/service.ctmpl
      - ./container/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - SERVICE_NAME=nginx-proxy

  auth-service:
    build: ./container/auth-service/
    image: microservice:auth-service
    container_name: auth-service
    depends_on:
      - registrator
    expose:
      - "80"
    environment:
      - SERVICE_80_CHECK_TCP=true
      - SERVICE_80_CHECK_INTERVAL=5s
      - SERVICE_80_CHECK_TIMEOUT=1s
      - SERVICE_80_NAME=auth-service
      - SERVICE_TAGS=api

  api1:
    build: ./container/node/
    image: microservice:nodeapi
    container_name: api1
    depends_on:
      - registrator
    expose:
      - "80"
    environment:
      - SERVICE_80_CHECK_HTTP=/
      - SERVICE_80_CHECK_INTERVAL=5s
      - SERVICE_80_CHECK_TIMEOUT=1s
      - SERVICE_80_NAME=hello
      - SERVICE_TAGS=api,public

  api2:
    build: ./container/node/
    image: microservice:nodeapi
    container_name: api2
    depends_on:
      - registrator
    expose:
      - "80"
    environment:
      - SERVICE_80_CHECK_HTTP=/
      - SERVICE_80_CHECK_INTERVAL=5s
      - SERVICE_80_CHECK_TIMEOUT=1s
      - SERVICE_80_NAME=hello
      - SERVICE_TAGS=api,public

  api3:
    build: ./container/node/
    image: microservice:nodeapi
    container_name: api3
    depends_on:
      - registrator
    expose:
      - "80"
    environment:
      - SERVICE_80_CHECK_HTTP=/
      - SERVICE_80_CHECK_INTERVAL=5s
      - SERVICE_80_CHECK_TIMEOUT=1s
      - SERVICE_80_NAME=secure
      - SERVICE_TAGS=api,public,protected

